name: Build and push image

on:
  push:
    branches: [ master ]

jobs:
  build-and-push-image:
    uses: Matheus-Merlos/infrastructure/.github/workflows/create_task_definition.yaml@master
    with:
      image-name: neon-bot
      cpu: 256
      memory: 512
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      DOTENV_CONTENT: ${{ secrets.DOTENV_CONTENT }}
