name: Deploy to EC2

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Add environment variables and start the bot
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo systemctl stop neon-bot

            cd ~/neon-bot

            echo "
            DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }}

            DB_FILE_NAME=file:db.sqlite3

            ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY }}
            SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_REGION=${{ secrets.AWS_REGION }}
            BUCKET_NAME=${{ secrets.BUCKET_NAME }}
            " > .env

            git checkout master
            git pull

            npm install
            npm run database:push

            sudo systemctl start neon-bot
