name: Deploy to EC2

on:
  push:
    branches: [ master ]
    paths:
    - 'src/**'
  workflow_dispatch:

jobs:
  get-server-dns:
    name: Get Server DNS
    uses: Matheus-Merlos/infrastructure/.github/workflows/neon_bot_server_dns.yaml@master
    secrets:
      TERRAFORM_AWS_ACCESS_KEY_ID: ${{ secrets.TERRAFORM_USER_ACCESS_KEY_ID}}
      TERRAFORM_AWS_SECRET_ACCESS_KEY: ${{ secrets.TERRAFORM_USER_SECRET_ACCESS_KEY }}

  cleanup:
    runs-on: ubuntu-latest
    needs: get-server-dns
    steps:
      - name: Cleanup old release
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ needs.get-server-dns.outputs.server-dns }}
          username: admin
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo systemctl stop neon-bot

            cd /home/admin/neon-bot

            rm -rf commands db strategies decorators factories node_modules utils || true
            rm .env client.js drizzle-dev.config.js drizzle-prod.config.js main.js package-lock.json package.json || true


  deploy:
    runs-on: ubuntu-latest
    needs: [get-server-dns, cleanup]
    steps:
      - name: Bring code to container
        uses: actions/checkout@v4


      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20


      - name: Build Typescript project
        run: |
          npm ci
          npx tsc


      - name: Copy build files to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ needs.get-server-dns.outputs.server-dns }}
          username: admin
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "dist/"
          target: "/home/admin/neon-bot"
          strip_components: 1


      - name: Copy dependencies to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ needs.get-server-dns.outputs.server-dns }}
          username: admin
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "package.json,package-lock.json"
          target: "/home/admin/neon-bot"


      - name: Add environment variables and start the bot
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ needs.get-server-dns.outputs.server-dns }}
          username: admin
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/neon-bot

            echo "${{ secrets.DOTENV_CONTENT }}" > .env

            npm install --omit=dev

            npx drizzle-kit generate --config=./drizzle-prod.config.js
            npx drizzle-kit migrate --config=./drizzle-prod.config.js

            sudo systemctl start neon-bot
