name: Docs website test

on:
  push:
    paths:
      - 'docs/**'

defaults:
  run:
    working-directory: ./docs

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from docs
        uses: actions/checkout@v4

      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          npm ci
          npx playwright install --with-deps

      - name: Create and seed database
        run: |
          export DATABASE_URL="db.sqlite3"
          npm run makemigrations
          npm run migrate

          ts-node ./src/lib/seed.ts

      - name: Run e2e tests
        run: npx playwright test

      - name: Upload-artifact
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: playwright-report
          path: playwright
          retention-days: 5

